# Generated by Django 2.2.20 on 2021-11-23 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0002_auto_20211122_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
