# Generated by Django 2.2.20 on 2021-11-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0004_timeentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name': 'time entry', 'verbose_name_plural': 'time entries'},
        ),
    ]
